[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
    return full_UI_table
'''
position = "before"
payload = '''
    local function set_quirky(_key)
        desc_nodes = {}
        localize{type = 'descriptions', key = _key, set = "Quirky", nodes = desc_nodes, vars = {}}
        full_UI_table.main = desc_nodes
    end
    if not G.PROFILES[G.SETTINGS.profile].dequirk then
	    G.PROFILES[G.SETTINGS.profile].dequirk = {}
    end
    if ((((not QRK.table_contains(G.PROFILES[G.SETTINGS.profile].dequirk, _c.key)) or QRK.config.mode[2]) and not QRK.config.mode[3]) or
    (QRK.config.mode[3] and _c.quirked)) and _c.unlocked and not hide_desc then
        if G.localization.descriptions.Quirky[_c.key] then
            set_quirky(_c.key)
        elseif G.localization.descriptions.Quirky[_c.key.."_"..1] then
            local entries = {}
            local function get_entries(number)
                if G.localization.descriptions.Quirky[_c.key.."_"..number] then
                    entries[#entries+1] = _c.key.."_"..number
                    get_entries(number+1)
                end
            end
            get_entries(1)
            set_quirky(pseudorandom_element(entries))
        end
    end
'''
match_indent = true